(ns textiletrade.render-html
  "Build-time HTML renderer for `docs/samples/operator-console.html`.

  Closes flagship checklist item 2 for this repo (com-junkawasaki/root
  ADR-2607189300, Wave 6): `docs/samples/operator-console.html` existed
  here as a HAND-WRITTEN stub (raw hex colors, numbers typed by a human,
  no generator at all). This namespace replaces it with a page that is
  GENERATED by driving the REAL actor stack --
  `textiletrade.operation` (a langgraph StateGraph) -> `textiletrade.governor`
  (the independent Textile Trading Governor) -> `textiletrade.store`
  (the SSoT + append-only audit ledger) -- and rendering only what that
  run actually produced.

  Nothing on the page is a literal a human typed:

    - every textile-order row is read back out of the real seeded store
      AFTER the scenario has mutated it (`:dispatched?`/`:invoiced?`/
      `:dispatch-number`/`:invoice-number` are the real post-commit
      values written by `textiletrade.registry`);
    - every audit-ledger row is a real fact appended by the actor's own
      `:commit`/`:hold` nodes;
    - every HARD-hold rule and Japanese `:detail` string is the
      governor's own output, not a paraphrase;
    - the action-gate table is derived from this repo's own
      `textiletrade.phase/phases` + `textiletrade.governor/high-stakes`
      data structures rather than described by hand, so it cannot drift
      away from the code;
    - the jurisdiction table is derived from `textiletrade.facts`.

  DETERMINISM: the store carries no clock, the ledger is an ordered
  vector, `all-textile-orders` sorts by `:id`, the registry numbers are
  jurisdiction-scoped sequences, and no timestamp is rendered into the
  page. Two consecutive runs are byte-identical (verified by `cmp`).

  Usage: `clojure -M:dev:render-html [out-file]`
  (default `docs/samples/operator-console.html`)."
  (:require [clojure.string :as str]
            [jp-go-dds.skin :as skin]
            [langgraph.graph :as g]
            [textiletrade.facts :as facts]
            [textiletrade.governor :as governor]
            [textiletrade.operation :as op]
            [textiletrade.phase :as phase]
            [textiletrade.store :as store]))

(def ^:private operator
  "The same operator context this repo's own `textiletrade.sim` driver
  uses -- a phase-3 trading supervisor."
  {:actor-id "op-1" :actor-role :trading-supervisor :phase 3})

;; ----------------------------- the real run -----------------------------

(defn- exec! [actor tid request]
  (g/run* actor {:request request :context operator} {:thread-id tid}))

(defn- approve! [actor tid]
  (g/run* actor {:approval {:status :approved :by "op-1"}}
          {:thread-id tid :resume? true}))

(defn- step!
  "Runs ONE real operation through the compiled actor graph and, when the
  graph interrupts for a human (`:escalate`), resumes it with a real
  approval. Records the disposition the graph ACTUALLY reached on each
  pass, so the console's route column is observed rather than asserted.
  Returns the recorded route map."
  [actor runs tid request]
  (let [r1 (exec! actor tid request)
        d1 (get-in r1 [:state :disposition])
        r2 (when (= :escalate d1) (approve! actor tid))
        d2 (some-> r2 (get-in [:state :disposition]))
        run {:thread-id tid
             :op (:op request)
             :subject (:subject request)
             :first-pass d1
             :final (or d2 d1)
             :confidence (get-in (or r2 r1) [:state :verdict :confidence])}]
    (swap! runs conj run)
    run))

(defn run-demo!
  "Drives a fresh seeded store through a scenario that reaches EVERY
  disposition this actor can produce, using this repo's own seeded
  textile-order ids (`to-1`..`to-8`, `textiletrade.store/demo-data`) and
  its own ops (`:order/intake`, `:supply-chain/verify`,
  `:delivery/dispatch`, `:invoice/settle`):

    to-1  full clean lifecycle -- intake (phase-3 auto-commit, the only
          auto-eligible op), supply-chain verification (escalates,
          approved), goods dispatch (ALWAYS escalates, approved) and
          invoice settlement (ALWAYS escalates, approved).
    to-2  supply-chain verification for jurisdiction ATL -- no official
          spec-basis in `textiletrade.facts/catalog` -> HARD hold
          (`:no-spec-basis`). Never reaches a human.
    to-3  verified, then dispatch HARD-holds on `:credit-uncleared`.
    to-4  verified, then dispatch HARD-holds on `:contract-missing`.
    to-5  verified, then dispatch HARD-holds on
          `:counterparty-sanctions-flag-unresolved`.
    to-6  verified, then dispatch HARD-holds on
          `:forced-labor-presumption-unrebutted` -- this vertical's
          domain-defining check (Xinjiang origin, USA jurisdiction,
          NEITHER rebuttal fact on file).
    to-7  the SAME Xinjiang origin WITH both rebuttal facts documented
          -> dispatches cleanly (escalates for the ordinary human
          sign-off, approved). Proves the presumption is genuinely
          REBUTTABLE, not a blanket regional ban.
    to-8  the SAME Xinjiang origin with NEITHER rebuttal fact, but
          jurisdiction JPN (no binding forced-labor import-ban statute)
          -> dispatches cleanly. Proves the check is JURISDICTION-gated.
    to-1  dispatched a SECOND time -> HARD hold (`:already-dispatched`).
    to-1  invoiced a SECOND time  -> HARD hold (`:already-invoiced`).

  Seven HARD holds, none of which is offered to a human, alongside a
  fully approved clean path. Returns {:db .. :runs [..]}."
  []
  (let [db (store/seed-db)
        actor (op/build db)
        runs (atom [])]
    (step! actor runs "to-1-intake"
           {:op :order/intake :subject "to-1"
            :patch {:id "to-1" :counterparty "Meridian Apparel Wholesale LLC"}})
    (step! actor runs "to-1-verify" {:op :supply-chain/verify :subject "to-1"})
    (step! actor runs "to-1-dispatch" {:op :delivery/dispatch :subject "to-1"})
    (step! actor runs "to-1-invoice" {:op :invoice/settle :subject "to-1"})

    (step! actor runs "to-2-verify" {:op :supply-chain/verify :subject "to-2"})

    (step! actor runs "to-3-verify" {:op :supply-chain/verify :subject "to-3"})
    (step! actor runs "to-3-dispatch" {:op :delivery/dispatch :subject "to-3"})

    (step! actor runs "to-4-verify" {:op :supply-chain/verify :subject "to-4"})
    (step! actor runs "to-4-dispatch" {:op :delivery/dispatch :subject "to-4"})

    (step! actor runs "to-5-verify" {:op :supply-chain/verify :subject "to-5"})
    (step! actor runs "to-5-dispatch" {:op :delivery/dispatch :subject "to-5"})

    (step! actor runs "to-6-verify" {:op :supply-chain/verify :subject "to-6"})
    (step! actor runs "to-6-dispatch" {:op :delivery/dispatch :subject "to-6"})

    (step! actor runs "to-7-verify" {:op :supply-chain/verify :subject "to-7"})
    (step! actor runs "to-7-dispatch" {:op :delivery/dispatch :subject "to-7"})

    (step! actor runs "to-8-verify" {:op :supply-chain/verify :subject "to-8"})
    (step! actor runs "to-8-dispatch" {:op :delivery/dispatch :subject "to-8"})

    (step! actor runs "to-1-dispatch-again" {:op :delivery/dispatch :subject "to-1"})
    (step! actor runs "to-1-invoice-again" {:op :invoice/settle :subject "to-1"})

    {:db db :runs @runs}))

;; ----------------------------- rendering helpers -----------------------------

(defn- esc [v]
  (-> (str v)
      (str/replace "&" "&amp;")
      (str/replace "<" "&lt;")
      (str/replace ">" "&gt;")
      (str/replace "\"" "&quot;")))

(defn- label [v] (if (keyword? v) (name v) (str v)))

(defn- clip
  "Deterministic display clip -- long legal-basis citations are real
  actor output but would otherwise dominate the table."
  [n s]
  (let [s (str s)]
    (if (> (count s) n) (str (subs s 0 n) "…") s)))

(defn- yes-no [b] (if b "yes" "no"))

(defn- route-badge [{:keys [first-pass final]}]
  (cond
    (= :hold first-pass) "<span class=\"critical\">HARD hold · never offered to a human</span>"
    (and (= :escalate first-pass) (= :commit final)) "<span class=\"warn\">human approved → committed</span>"
    (= :commit first-pass) "<span class=\"ok\">auto-committed (governor-clean)</span>"
    :else (str "<span class=\"muted\">" (esc (label final)) "</span>")))

;; ----------------------------- sections -----------------------------

(defn- order-row [ledger {:keys [id order-id goods-kind origin-region counterparty
                                 jurisdiction dispatched? invoiced?
                                 dispatch-number invoice-number] :as to}]
  (let [last-fact (last (filter #(= (:subject %) id) ledger))
        status (cond
                 (nil? last-fact) "<span class=\"muted\">no activity</span>"
                 (= :governor-hold (:t last-fact))
                 (str "<span class=\"critical\">HARD hold · "
                      (esc (label (-> last-fact :basis first))) "</span>")
                 :else "<span class=\"ok\">committed</span>")
        flagged? (facts/flagged-origin? origin-region)
        triggered? (facts/forced-labor-presumption-triggered? to)]
    (format (str "        <tr><td><code>%s</code></td><td>%s</td><td>%s</td><td>%s</td>"
                 "<td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>")
            (esc id) (esc order-id) (esc goods-kind)
            (str (esc origin-region)
                 (when flagged?
                   (str " <span class=\"" (if triggered? "critical" "muted") "\">flagged origin"
                        (if triggered? " · presumption applies" " · jurisdiction not binding")
                        "</span>")))
            (esc counterparty) (esc jurisdiction)
            (if dispatched?
              (str "<span class=\"ok\">dispatched</span> <code>" (esc dispatch-number) "</code>")
              "<span class=\"muted\">not dispatched</span>")
            (if invoiced?
              (str "<span class=\"ok\">invoiced</span> <code>" (esc invoice-number) "</code>")
              "<span class=\"muted\">not invoiced</span>")
            status)))

(defn- evidence-row [{:keys [id jurisdiction credit-cleared? contract-terms
                             sanctions-screened?
                             supply-chain-traceability-documented?
                             forced-labor-rebuttal-evidence-on-file?]}]
  (format (str "        <tr><td><code>%s</code></td><td>%s</td><td>%s</td><td>%s</td>"
               "<td>%s</td><td>%s</td><td>%s</td></tr>")
          (esc id) (esc jurisdiction)
          (yes-no credit-cleared?)
          (if (str/blank? (str contract-terms))
            "<span class=\"critical\">none on file</span>"
            (esc contract-terms))
          (yes-no sanctions-screened?)
          (yes-no supply-chain-traceability-documented?)
          (yes-no forced-labor-rebuttal-evidence-on-file?)))

(defn- gate-rows
  "Derived from this repo's OWN `textiletrade.phase/phases` +
  `textiletrade.governor/high-stakes`, so the table cannot drift away
  from the code it describes."
  []
  (let [ph phase/default-phase
        {:keys [label writes auto]} (get phase/phases ph)]
    (for [o (sort-by str phase/write-ops)]
      (format "        <tr><td><code>%s</code></td><td>%s</td></tr>"
              (esc o)
              (cond
                (contains? governor/high-stakes o)
                "<span class=\"warn\">ALWAYS human approval · never in any phase's <code>:auto</code> set</span>"
                (contains? auto o)
                (str "<span class=\"ok\">phase " ph " (" (esc label)
                     "): auto-commit when governor-clean</span>")
                (contains? writes o)
                (str "<span class=\"warn\">phase " ph ": human approval (not auto-eligible)</span>")
                :else
                (str "<span class=\"critical\">phase " ph ": disabled → hold</span>"))))))

(defn- hold-rows
  "One row per HARD rule the governor ACTUALLY fired in this run, with
  the governor's own `:detail` text."
  [ledger]
  (let [holds (filter #(= :governor-hold (:t %)) ledger)
        by-rule (->> holds
                     (mapcat (fn [h] (map (fn [v] [(:rule v) (:subject h) (:detail v) (:op h)])
                                          (:violations h))))
                     (group-by first))]
    (for [rule (sort-by str (keys by-rule))
          :let [entries (get by-rule rule)]]
      (format "        <tr><td><code>%s</code></td><td class=\"num\">%d</td><td><code>%s</code></td><td>%s</td></tr>"
              (esc rule)
              (count entries)
              (esc (str/join ", " (sort (distinct (map second entries)))))
              (esc (clip 220 (nth (first entries) 2)))))))

(defn- ledger-row [{:keys [t op subject disposition basis violations summary]}]
  (let [hold? (= :governor-hold t)]
    (format (str "        <tr><td>%s</td><td><code>%s</code></td><td><code>%s</code></td>"
                 "<td>%s</td><td>%s</td></tr>")
            (if hold?
              "<span class=\"critical\">governor-hold</span>"
              (str "<span class=\"ok\">" (esc (label t)) "</span>"))
            (esc op) (esc subject)
            (esc (label disposition))
            (esc (clip 200
                       (if hold?
                         (str (str/join ", " (map label basis)) " — "
                              (str/join " / " (map :detail violations)))
                         (str summary
                              (when (seq basis)
                                (str " [" (str/join "; " (map label basis)) "]")))))))))

(defn- jurisdiction-rows
  "Derived from `textiletrade.facts` for every jurisdiction the seeded
  orders actually use -- including the ones with NO spec-basis, which is
  exactly what produces the `:no-spec-basis` hold above."
  [orders]
  (for [j (sort (distinct (map :jurisdiction orders)))
        :let [sb (facts/spec-basis j)
              binding? (facts/forced-labor-import-ban-binding? j)]]
    (format "        <tr><td><code>%s</code></td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>"
            (esc j)
            (if sb (esc (:owner-authority sb))
                "<span class=\"critical\">no spec-basis — proposals HOLD</span>")
            (if sb (esc (clip 160 (:legal-basis sb))) "—")
            (if sb (esc (str/join ", " (facts/evidence-checklist j))) "—")
            (if binding?
              "<span class=\"warn\">binding forced-labor import ban</span>"
              "<span class=\"muted\">none binding</span>"))))

(defn- registry-rows [records kind-label]
  (for [r records]
    (format "        <tr><td><code>%s</code></td><td>%s</td><td><code>%s</code></td><td>%s</td><td>%s</td></tr>"
            (esc (get r "record_id")) (esc kind-label)
            (esc (get r "textile_order_id")) (esc (get r "jurisdiction"))
            (if (get r "immutable")
              "<span class=\"ok\">immutable draft</span>"
              "<span class=\"muted\">—</span>"))))

(defn- run-rows [runs]
  (for [r runs]
    (format "        <tr><td><code>%s</code></td><td><code>%s</code></td><td><code>%s</code></td><td class=\"num\">%s</td><td>%s</td></tr>"
            (esc (:thread-id r)) (esc (:op r)) (esc (:subject r))
            (esc (:confidence r))
            (route-badge r))))

;; ----------------------------- document -----------------------------

(defn render
  "Renders the whole operator-console document from the result of
  `run-demo!` ({:db .. :runs ..}). Every cell comes from that run."
  [{:keys [db runs]}]
  (let [ledger (vec (store/ledger db))
        orders (vec (store/all-textile-orders db))
        holds (filterv #(= :governor-hold (:t %)) ledger)
        commits (filterv #(= :committed (:t %)) ledger)
        auto (filterv #(= :commit (:first-pass %)) runs)
        approved (filterv #(and (= :escalate (:first-pass %))
                                (= :commit (:final %))) runs)
        cov (facts/coverage)]
    (str
     "<!doctype html>\n<html lang=\"en\"><head><meta charset=\"utf-8\">"
     "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
     "<title>cloud-itonami-isic-4641 · textile/apparel/footwear wholesale — Operator Console</title>"
     "<style>" (skin/dds+skin) "</style></head><body>\n"
     "<header class=\"bar\">\n"
     "  <h1>Wholesale of textiles, clothing and footwear (ISIC 4641) — Operator Console</h1>\n"
     "</header>\n"
     "<p><span class=\"badge\">read-only sample</span> <span class=\"badge\">governor-gated</span> "
     "<span class=\"badge\">dispatch &amp; invoice always human-approved</span></p>\n"
     "<p class=\"subtitle\">Generated at build time by <code>textiletrade.render-html</code> "
     "(<code>clojure -M:dev:render-html</code>) by actually running "
     "<code>textiletrade.operation</code> → <code>textiletrade.governor</code> → "
     "<code>textiletrade.store</code>. Nothing on this page is hand-written output: every id, "
     "number, disposition and hold reason below was produced by that run.</p>\n"

     "<section class=\"card\">\n"
     "  <h2>Run summary</h2>\n"
     "  <table>\n"
     "    <thead><tr><th>Measure</th><th>Value</th></tr></thead>\n"
     "    <tbody>\n"
     (format "      <tr><td>Operations run through the actor graph</td><td class=\"num\">%d</td></tr>\n" (count runs))
     (format "      <tr><td>Ledger facts appended</td><td class=\"num\">%d</td></tr>\n" (count ledger))
     (format "      <tr><td>Committed (SSoT mutated)</td><td class=\"num\">%d</td></tr>\n" (count commits))
     (format "      <tr><td>Auto-committed without a human</td><td class=\"num\">%d</td></tr>\n" (count auto))
     (format "      <tr><td>Escalated then human-approved</td><td class=\"num\">%d</td></tr>\n" (count approved))
     (format "      <tr><td><span class=\"critical\">HARD governor holds (never offered to a human)</span></td><td class=\"num\">%d</td></tr>\n" (count holds))
     (format "      <tr><td>Goods dispatches registered</td><td class=\"num\">%d</td></tr>\n" (count (store/dispatch-history db)))
     (format "      <tr><td>Invoices settled</td><td class=\"num\">%d</td></tr>\n" (count (store/invoice-history db)))
     (format "      <tr><td>Governor confidence floor</td><td class=\"num\">%s</td></tr>\n" governor/confidence-floor)
     "    </tbody>\n"
     "  </table>\n"
     "</section>\n"

     "<section class=\"card\">\n"
     "  <h2>Textile orders after the run</h2>\n"
     "  <p class=\"muted\">Read back out of the SSoT once the scenario finished — dispatch and "
     "invoice numbers are the real jurisdiction-scoped sequences <code>textiletrade.registry</code> "
     "assigned at commit time.</p>\n"
     "  <table>\n"
     "    <thead><tr><th>Order</th><th>Order id</th><th>Goods</th><th>Origin region</th>"
     "<th>Counterparty</th><th>Jur.</th><th>Dispatch</th><th>Invoice</th><th>Last fact</th></tr></thead>\n"
     "    <tbody>\n"
     (str/join "\n" (map (partial order-row ledger) orders)) "\n"
     "    </tbody>\n"
     "  </table>\n"
     "</section>\n"

     "<section class=\"card\">\n"
     "  <h2>Counterparty evidence ground truth</h2>\n"
     "  <p class=\"muted\">The facts the Textile Trading Governor re-reads independently of the "
     "advisor's self-report. A single <code>no</code> in the wrong column is what produced the "
     "corresponding HARD hold below.</p>\n"
     "  <table>\n"
     "    <thead><tr><th>Order</th><th>Jur.</th><th>Credit cleared</th><th>Contract terms</th>"
     "<th>Sanctions screened</th><th>Supply-chain traced</th><th>Forced-labor rebuttal on file</th></tr></thead>\n"
     "    <tbody>\n"
     (str/join "\n" (map evidence-row orders)) "\n"
     "    </tbody>\n"
     "  </table>\n"
     "</section>\n"

     "<section class=\"card\">\n"
     "  <h2>Action gate (Textile Trading Governor × rollout phase)</h2>\n"
     "  <p class=\"muted\">Derived from <code>textiletrade.phase/phases</code> and "
     "<code>textiletrade.governor/high-stakes</code> at render time. HARD violations cannot be "
     "overridden by an approver; <code>:delivery/dispatch</code> and <code>:invoice/settle</code> "
     "are absent from every phase's <code>:auto</code> set, so two independent layers agree that "
     "actuation is always a human call.</p>\n"
     "  <table>\n"
     "    <thead><tr><th>Op</th><th>Gate</th></tr></thead>\n"
     "    <tbody>\n"
     (str/join "\n" (gate-rows)) "\n"
     "    </tbody>\n"
     "  </table>\n"
     "</section>\n"

     "<section class=\"card\">\n"
     "  <h2>HARD holds this run produced</h2>\n"
     "  <p class=\"muted\">One row per rule the governor actually fired, with its own "
     "<code>:detail</code> text verbatim. None of these was offered to a human approver.</p>\n"
     "  <table>\n"
     "    <thead><tr><th>Rule</th><th>Fired</th><th>Orders</th><th>Governor detail</th></tr></thead>\n"
     "    <tbody>\n"
     (str/join "\n" (hold-rows ledger)) "\n"
     "    </tbody>\n"
     "  </table>\n"
     "</section>\n"

     "<section class=\"card\">\n"
     "  <h2>Operations, in order</h2>\n"
     "  <p class=\"muted\">The disposition each graph run actually reached — observed from "
     "<code>langgraph.graph/run*</code>, including the resume pass after a human approval.</p>\n"
     "  <table>\n"
     "    <thead><tr><th>Thread</th><th>Op</th><th>Order</th><th>Confidence</th><th>Route</th></tr></thead>\n"
     "    <tbody>\n"
     (str/join "\n" (run-rows runs)) "\n"
     "    </tbody>\n"
     "  </table>\n"
     "</section>\n"

     "<section class=\"card\">\n"
     "  <h2>Audit ledger (this run)</h2>\n"
     "  <p class=\"muted\">Append-only decision-fact log written by the actor's own "
     "<code>:commit</code> and <code>:hold</code> nodes. Long legal-basis citations are clipped "
     "for display only.</p>\n"
     "  <table>\n"
     "    <thead><tr><th>Fact</th><th>Op</th><th>Order</th><th>Disposition</th><th>Basis / violation</th></tr></thead>\n"
     "    <tbody>\n"
     (str/join "\n" (map ledger-row ledger)) "\n"
     "    </tbody>\n"
     "  </table>\n"
     "</section>\n"

     "<section class=\"card\">\n"
     "  <h2>Registry drafts</h2>\n"
     "  <p class=\"muted\">The unsigned book-of-record drafts "
     "<code>textiletrade.registry</code> constructed at commit time. Signature is the operator's "
     "act, not this actor's.</p>\n"
     "  <table>\n"
     "    <thead><tr><th>Record</th><th>Kind</th><th>Order</th><th>Jur.</th><th>Status</th></tr></thead>\n"
     "    <tbody>\n"
     (str/join "\n" (concat (registry-rows (store/dispatch-history db) "textile-dispatch-draft")
                            (registry-rows (store/invoice-history db) "textile-invoice-draft"))) "\n"
     "    </tbody>\n"
     "  </table>\n"
     "</section>\n"

     "<section class=\"card\">\n"
     "  <h2>Jurisdiction spec-basis</h2>\n"
     "  <p class=\"muted\">" (esc (:note cov)) "</p>\n"
     "  <table>\n"
     "    <thead><tr><th>Jur.</th><th>Owner authority</th><th>Legal basis</th>"
     "<th>Required evidence</th><th>Forced-labor import ban</th></tr></thead>\n"
     "    <tbody>\n"
     (str/join "\n" (jurisdiction-rows orders)) "\n"
     "    </tbody>\n"
     "  </table>\n"
     "</section>\n"

     "<footer>\n"
     "  <p>Generated by <code>textiletrade.render-html</code> from a real "
     "<code>textiletrade.operation</code> run. Deterministic: no timestamps, no random ids — "
     "re-running against the same seed produces a byte-identical file. Regenerate with "
     "<code>clojure -M:dev:render-html</code>.</p>\n"
     "</footer>\n"
     "</body></html>\n")))

(defn -main [& args]
  (let [out (or (first args) "docs/samples/operator-console.html")
        {:keys [db runs] :as result} (run-demo!)
        ledger (vec (store/ledger db))
        holds (filterv #(= :governor-hold (:t %)) ledger)]
    ;; Build-time invariant, not a convention: a console that shows no HARD
    ;; hold is not evidence that the governor works. Refuse to write it.
    (when (zero? (count holds))
      (throw (ex-info (str "refusing to write " out
                           ": the scenario produced ZERO :governor-hold ledger entries. "
                           "The operator console must demonstrate at least one HARD hold "
                           "(a hold that never reaches a human) -- otherwise the page is "
                           "not evidence that the Textile Trading Governor can reject a "
                           "proposal at all.")
                      {:out out
                       :ledger-facts (count ledger)
                       :governor-holds 0
                       :ops-run (count runs)})))
    (spit out (render result) :encoding "UTF-8")
    (println "wrote" out
             (str "(" (count ledger) " ledger facts, "
                  (count holds) " HARD governor holds, "
                  (count (filter #(= :committed (:t %)) ledger)) " commits, "
                  (count (store/dispatch-history db)) " dispatches, "
                  (count (store/invoice-history db)) " invoices)"))))
